world_name: world # World to run the plugin in
language: french # language to use
enable_metrics: true # Please, keep this value to yes, it helps me fixing bugs & get feedbacks about the plugi
enable_auto_update: true # Enable auto-update, keep this as true to get the latest version of this plugin
enable_mysql_storage: false # Enable MySQL data storage
enable_community_version: false # Enable/disable community mod
min_player_per_group: 6 # Number of player required to start a game in community Mode
player_location_refresh_rate: 10 # Number of tick between each player's HUD location refreshs.
enable_block_warning: true